apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-kyma-mock
  labels:
    app: example-kyma-mock
spec:
  selector:
    matchLabels:
      app: example-kyma-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: example-kyma-mock
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/incubator/varkes-example-kyma-mock:latest
        imagePullPolicy: Always
        name: example-kyma-mock
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: example-kyma-mock
  labels:
    app: example-kyma-mock
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: example-kyma-mock
