apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-combined-openapi-mock
  labels:
    app: example-combined-openapi-mock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-combined-openapi-mock
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/incubator/varkes-example-combined-openapi-mock:0.1.0
        imagePullPolicy: Always
        name: example-combined-openapi-mock
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: example-combined-openapi-mock
  labels:
    app: example-combined-openapi-mock
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: example-combined-openapi-mock
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    app: example-combined-openapi-mock
  name: example-combined-openapi-mock
spec:
  hostname: example-combined-openapi-mock
  service:
    name: example-combined-openapi-mock
    port: 10000